### PR TITLE
Add community, advisor and staff to /team

### PR DESCRIPTION
**Pull request by BenJam**
Closes librariesio/supporters#20

### CODE REVIEW

**Comment by andrew** [comment]
It's a little broken on mobile:
screen shot 2017-02-24 at 5 56 13 pm

**Comment by BenJam** [comment]
Sigh. I'll fix it up!

**Comment by BenJam** [comment]
picking this up now. @andrew any comments on preferred approach? I could (for instance) re-use a partial from https://libraries.io/github/librariesio/bibliothecary/contributors for the top section.

**Comment by andrew** [comment]
@BenJam I think you can fix it for small screens by replacing the `col-sm-X` with `col-md-X`, that way each user section will become 100% width on small screens

**Comment by BenJam** [comment]
@andrew tried a couple of ways, no luck, any chance you could take a peek?

**Comment by andrew** [comment]
@BenJam checking it out now

**Pull request merged**
