### PR TITLE
Create RepositoryHost classes

### PR DESCRIPTION
**Pull request by maclover7**
If 👍 on this architecture, I can begin to move code over to the different `RepositoryHost::Base` subclasses.

cc @andrew

### CODE REVIEW

**Comment by andrew** [comment]
👍👍👍

**Comment by maclover7** [comment]
@andrew if possible, can we start off with just Github, and see how that goes? I can continue porting over the different hosts after Github goes live for a short while.

**Comment by andrew** [comment]
@maclover7 yeah we can do, would be good to get some test coverage on these changes, I also was imagining that we'd make a new instance of the RepositoryHost class, passing the Repository object and then using instance methods where it makes sense

**Comment by maclover7** [comment]
@andrew updated to pass around the `Repository` object; what do you think about migrating over methods at a time, instead of "hosts" at a time? Also, I can try and add test coverage for the methods in a separate PR, to keep this one smaller.

**Comment by andrew** [comment]
Methods rather than hosts sounds good to me, and tests can come in a later PR 👍

**Comment by maclover7** [comment]
@andrew updated the PR to move all main business logic methods to the new classes. I'm happy to do a little more cleanup in a followup PR

**Comment by andrew** [comment]
That's looking great!

**Comment by maclover7** [comment]
👍

**Pull request merged**
