### PR TITLE
Un-extraction of the github_urls gem

### PR DESCRIPTION
**Pull request by maclover7**
To have `BitbucketURLParser`, `GitlabURLParser`, and `GithubURLParser` all live in the same repository.

### CODE REVIEW

**Comment by maclover7** [comment]
cc @andrew

**Comment by andrew** [comment]
👌 Could do with a few tests for `BitbucketURLParser` and `GitlabURLParser` if you're up for it?

**Comment by maclover7** [comment]
@andrew updated

**Comment by andrew** [comment]
Amazing, thanks so much @maclover7!!!

**Comment by maclover7** [comment]
👍

**Pull request merged**
