### PR TITLE
Added Stats for PR and Issues for the Last Year

### PR DESCRIPTION
**Pull request by mikeyoung85**
Added a query to get issues for a repository through the V3 API. This calls returns both issues and pull requests together.

### CODE REVIEW

**Comment by mikeyoung85** [comment]
I should also note that I think this potentially will use quite a few API calls compared to the total issue and PR counts we are getting back from the graphql query in there now. Github treats PRs and Issues as the same and returns them in chunks of 100. So something big like `rails` has 45 pages of issues come back.

**Comment by havocp** [comment]
A couple of possible ways to reduce API use, since our current goal is just "see if the project is alive," could be:
  * only pull these 1-year issue counts if there are liveness concerns based on commits, i.e. if there are lots of commits in the time window, don't bother to compute the issue rate (probably an awkward special case, but...)
 * if the first few pages of results have enough issues/PRs to be a decent statistical sample ("enough" = I dunno, 100?) then we could just use that... or we could sample the first, middle, and last pages, if it's possible to know the total count and skip pages... since I guess the most recent items might tend to have a lower close rate. Or sample only the middle page maybe.

I don't know if this complexity is worthwhile yet - thoughts welcome - but suggesting ways we could limit API calls if we do need to.

**Comment by katzj** [comment]
My initial instinct is that we should limit how many pages we get back and call it good. If `rails/rails` has 45 pages for a year, then if we do 10, that'll cover the vast majority of cases. The outliers where we don't fetch them all will, I suspect, be active and so we'll get good enough with just that sample

Worth storing something specific so we know that happened but let's not overthink this

**Comment by mikeyoung85** [comment]
I've updated the query to not auto paginate and instead limits it to the latest 1000 issues/pull requests. I've added a flag in the stats that indicates if the results were truncated. Stats look like this now from the rails repository:

```ruby
{
  :one_year_open_issues=>99, 
  :one_year_closed_issues=>240, 
  :one_year_total_issues=>339,
  :one_year_issue_closure_rate=>0.7079646017699115, 
  :one_year_open_pull_requests=>129, 
  :one_year_closed_pull_requests=>532, 
  :one_year_total_pull_requests=>661, 
  :one_year_pull_request_closure_rate=>0.8048411497730711, 
  :issues_stats_truncated=>true
} 
```

**Pull request merged**
