### PR TITLE
Handle removed Pypi projects gracefully when fetching releases

### PR DESCRIPTION
**Pull request by tiegz**
fixes this error:

```
NoMethodError 
CheckStatusWorker@status
undefined method `map' for nil:NilClass @data["releases"].map do |version_number, details| ^^^^
```

### CODE REVIEW

**Comment by wenottingham** [comment]
does this have any data consequences beyond "silencing an error"

**Comment by tiegz** [comment]
nah, from what I can tell this is happening on "Removed" projects, so it makes sense that their releases would be empty.

**Comment by tiegz** [comment]
<rethinking this>

**Comment by tiegz** [comment]
I'm gonna close this. I think the error here is a rare race condition, where:

1) `Project#check_status`: we fetch the package url, and it 200s, so we skip the line that would mark it as "Removed"
2) the package is removed from pypi, which would then the package it to 404
3) a few lines of code after (1), we check `project.platform_class.deprecation_info(project)`, which pulls the package, but it's gone now so we don't get any data back

once this worker retries, it should halt on (1) and mark the package as "Removed", so I don't think we should bother messing with the Pypi ingestion code.

**Pull request closed without merging**
