### PR TITLE
Combine almost identical URL parsers

### PR DESCRIPTION
**Pull request by maclover7**
The Bitbucket and Gitlab URL parsers were almost identical, so it made
sense to just combine them, to avoid extreme code duplication.

### CODE REVIEW

**Comment by andrew** [comment]
👍 This is great, I think we can combine this with the https://github.com/librariesio/github_urls project too

**Comment by maclover7** [comment]
@andrew do we want to bring the parser from that gem into librariesio/libraries.io?

**Comment by andrew** [comment]
@maclover7 it was originally extracted from this repo and has a nice set of tests with it, would make sense to have them all in the same place, do you fancy bringing it back in with the test suite?

**Comment by maclover7** [comment]
👍 sure, I'll take a look!

**Comment by maclover7** [comment]
Opened #1192

**Pull request merged**
