### PR TITLE
Update links to open data release for v1.0.1

### PR DESCRIPTION
**Pull request by andrew**
Updated links to new zenodo release which should fix the zip errors people have been reporting: https://zenodo.org/record/833207

### CODE REVIEW

**Comment by BenJam** [comment]
maybe tighten up the leftmost div because the date is cutting in two. Might also be better to retain direct links to previous version(s) too.

**Comment by andrew** [comment]
@BenJam updated, how's this:

screen shot 2017-07-21 at 4 07 03 pm

**Comment by BenJam** [comment]
👍

**Comment by andrew** [comment]
Deploying now

**Pull request merged**
