### PR TITLE
Upgrade simplecov gem to 0.14.1

### LINKED ISSUE #1297: Upgrade simplecov to version 0.14.1
Libraries.io has found that there is a newer version of simplecov that this project depends on.

More info: https://libraries.io/rubygems/simplecov/0.14.1

### PR DESCRIPTION
**Pull request by abrophy**
Upgrade of the simplecov gem. Explicitly sets version in Gemfile to
0.14.1 and updates Gemfile.lock file.

Fixes #1297

### CODE REVIEW

**Comment by andrew** [comment]
Thanks! We don't set the absolute versions in Gemfile, as they are locked in Gemfile.lock, if you can remove that I'll get it merged.

**Comment by abrophy** [comment]
Sorry about that, will do!

**Comment by andrew** [comment]
You'll need to run 'bundle' again to update the lock file now that you've removed the explicit version

**Comment by abrophy** [comment]
Once more with feeling

**Comment by andrew** [comment]
🎉

**Pull request merged**
